language: java
jdk:
- oraclejdk8
sudo: false
cache:
  directories:
  - "$HOME/.gradle"
before_install:
- chmod +x publish.sh
install: true
script: "./gradlew clean build"
after_success:
- if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then ./publish.sh; fi
env:
  global:
  - CI_NAME=travis-ci
  - secure: "cdcIJrCgQgYqhtlEFtRBEQX85nldbkRFe0acD35EebF5dStgu/oKR21nZcMVlwJV4RlRvV1+ni2OQ2ZL6pMIQ6WPX+SHVscF+cPrMX3i4QV4+6/9LZprCLu3TmbY44mtvyKoJhzuQT13pE8fy92aufycKaLeaA0fYAGim03zMeYQ3VK/xXsR+0bQcVnsoA93h1eWyLCojYsuG7TLDcaK6bijxnDccpe7BAUlrAd7hTw7/5MfGwixzRdoMJPBQsKvsaQs0aZURKo8txAvPjyoseRH203wK+61HdeJnBDO8p2+xGoEVYuWDhEmj3URO97k6hbYNkesz0Rqc5Qkgh7fJS0h+90AHGvrH5TQpDnGN9WtXsUj2YMqVdBvysljUC2SmuS7jta0m4BBWrJpv0QpR90n7R9W1RfAssxVrwUfouFEK44q1zrZn/XP0m3Kw72tPsjUTZ7ntYQrpTkkmVvx2blhd1zsHTvcgND6gKwzYSzNfwo97tYvqMq6Kg9sze3bgkqKg9pO/c7yx2b6G/TdbSanTu4mfM2hhsL0/v+utBlWqMABLpqjpCGZCrfCVa1XqscXET3lw19fHfZbjm+a/tm7hOZuFuz24QO6/wM7T0DzZITdz6MQ7zTr8JE9IJ7GclUH0a+0tD05LxB4NSr9li7d3xKJkJTwJ9GHP9CjC+Y=" # bintray
  - secure: "sGTn5r9UYxRVtilFruvWwyXUYZQptdDlO7ER5juqwCjUTOIvRQxnSLOFv7kW5xwlddZq++r4Nu6zH70e8MNbhhccYRfQ486A7r9JblaQ327AqljUOVuN3NQs7RgaKeLWppIhusaDR/Nq6XWujdRli+sgXIJI70nbTwjWk99fGWu83huaIaYBSbkFIYnuWHlZSYWZy4Ano8souluSAOahtMBIwC1GJAyIuPmdYCQJVfxVBNEPqmwX/C7QRC5i4KpR2P8v93z5xFMwx5SgCDh5+CW9gYMxKlw8BAGTN/WzeVgGlZ9N/kUrr/UTPb79zEFqTeacf/4APOlAtePaobtC3zur9Hvc21lSSl5UGIhwLQGHnS63CD5cv7/l78uGvM120knI/Ww3afc7sUzIETXQ4PbS1pfYr0mA/K9a8OTH2COqIjccoX45hyPsns7PtcfKdy9z8z/7u4cjV0QJZrOmhUfEvhg6pya+W9GamTpl+8INuIhTpJOhfuxv0zydm4qDEn8BjbKu4HjD3nGmVVCi50COvHsI6wEgzxwJLSon4W3dMxJYlj3BzrjY6GtfO88T/C3OA2oj6yGJgkZRRiNPVR1yYXCRUkH595OdbCPRbXKM/QRDPjLbn5rzS9KMgqrOtSxyX1M9JGWt4V+edCpXCTy+3DlevafF6BESkBRolPA=" # bintray
